### ISSUE TITLE
Getting 400 bad request when sending hit from POSTMAN

### ISSUE THREAD

**Issue by shockalotti** [NHinternesch/gtm-server-client-custom-event-parser#1]
Hi, thanks for making this great template.

Nice and clean and well documented.

When testing, I get a hit sent via browser showing in my GTM-server preview mode. But for some reason, when sending the hit from POSTMAN (Windows 10 desktop app) I get 400 bad request.

Here's a view showing what I'm seeing:
https://share.getcloudapp.com/Z4uoB482

Wondering if you can share some light on this.

Many thanks!

**Comment by NHinternesch** [comment]
Hi, 

Thank you very much for testing and for your feedback! 
I just ran a test and I am receiving a 200 response when sending the GET request from postman (just like you are in the video). 

Here are some possible things to check (credit to Simo Ahava on MeasureSlack): 

- Usually, a 400 is returned when no client is claiming the request. Maybe you can doublecheck, whether the client is actively set up for the correct path in your GTM SS container
- When sending without a regular browser, GET requests need `withCredentials` set to `true` for them to appear in the Preview, as the Preview mode uses cookies to display the hits

Does any of that work for you? 
Thanks again for your feedback.

**Comment by shockalotti** [comment]
I think I've figured it out...

So the issue IS the _absence_ of a key header, but not `withCredentials`. The one that's needed is `X-Gtm-Server-Preview`. It's an option you can find in the GTM-Server Preview, top right corner (click the little link with 3 dots and `send requests manually` option appears in the drop.

Here's a quick video showing what I mean:
https://share.getcloudapp.com/12uA8WqA

Can't believe more people haven't mentioned this... not even Google. Honestly! I've been searching for an answer for DAYS.

I had a hunch it was something simple. Phew!
